site_name: PyLadies
site_url: https://pyladies.com
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
  language: en
plugins:
  - blog
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
    - name: Japanese
      link: /ja/
      lang: ja
    - name: Portuguese
      link: /pt-BR/
      lang: pt-BR
    - name: Spanish
      link: /es/
      lang: es
